### PR TITLE
Some minor additions

### PR DESCRIPTION
**Pull request by HagegeR**
hi,

first of all thank you for your contribution!

I looked at some other blogs and tried to put in this script everything that was in other blogs and incorporate them here...

I hope it'll work!

### CODE REVIEW

**Comment by mdegans** [comment]
Nice work! Very likely to merge this but have a few questions/comments:
- why curl?
- have you tested CUDA_FAST_MATH? I haven't run through the test suites with it enabled and disabled. If you run the tests and it doesn't break too much, i'll accept the change (warning, the tests take a long time to run).
- rather not have the jetson-clocks / power model stuff as it might break some systems if they're running on lower power modes (eg. a nano powered by micro-USB).

**Comment by HagegeR** [comment]
Firstly: thanks! I just tried to gather every other script in one...

> why curl?
Well, I thought partway to change the way things are downloaded,  but then I saw that no additional download was necessary so I left it and didn't use it. I thought that it couldn't hurt in case latter someone would want to download using curl.

> have you tested CUDA_FAST_MATH?

As I said I gathered every other script but currently I don't have a jetson nano on me to test it. I suppose this could lead to potential speed gains and that's probably the target when using that kind of hardware.

> rather not have the jetson-clocks

that's ok for me, I just thought that it was the fastest way to get the hardware ready.

So you want me to correct those or do you want to do it?

**Comment by mdegans** [comment]
Thanks for the corrections! Looking good, but there is still a small issue, however.
```
Get:1 https://repo.download.nvidia.com/jetson/common r32 InRelease [2,541 B]
Hit:2 https://repo.download.nvidia.com/jetson/t194 r32 InRelease                      
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic InRelease                   
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease           
Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Fetched 2,541 B in 2s (1,470 B/s)                 
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package zlib
```
I may be mistaken, but I think the dev package for zlib is `zlib1g-dev`. Please try that instead of zlib.
> I don't have a jetson nano on me to test it.

No worries. I will merge this into dev, test it, and fix. Thank you for your contributions!

**Comment by mdegans** [comment]
So, I'm testing a simple build now. So far so good. I'm not sure I'll have a chance to run the tests for CUDA_FAST_MATH within the next month or so, however, so I may leave that option. The last time somebody ran tests with that option on some more [things failed](https://devtalk.nvidia.com/default/topic/1049972/jetson-nano/opencv-cuda-python-with-jetson-nano/post/5342609/#5342609). It may be better to leave it up to people who explicity want to trade accuracy for speed.

**Comment by HagegeR** [comment]
I think it's good to leave options in the hands of the user.

But in my opinion, so much has changed since then that the bug is probably not there anymore, but maybe elsewhere... who knows

**Comment by mdegans** [comment]
Maybe. When I have time I will run tests with it on and off and see (or you're welcome to). My Xavier is almost done building. Looks good.

What CUDA_FAST_MATH does is reduce precision to gain speed, so it's kind of normal some tests fail because many might be expecting a certain result which won't be the same. Only thing I worry about is that being unexpected for some people who rely on the higher precision. It'll probably work fine for 90% of cases, but...

As to whether bugs are coming or going, I have no idea. I do know Nvidia doens't touch OpenCV. The cuda stuff is community maintained.

**Comment by HagegeR** [comment]
Yeah but I don't really expect people will try to do precision work on a jetson nano, I do expect them to want every FPS they can, at whatever cost

**Pull request merged**
